**Step1**: Import the necessary libraries

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Step2:** For the datafframe below, compute the mean of the data1 column using the labels from key1.

In [ ]:
df.groupby('key1')['data1'].mean()

**Step3:** Now compute the mean for `data1` grouped by both `key1` and `key2`

In [ ]:
df.groupby(['key1', 'key2'])['data1'].mean()

**Step4** Find the group sizes by `key1` and `key2`.

In [ ]:
df.groupby(['key1', 'key2']).size()

**Step5** Iterate over the data grouped by `key1` and \
generate a sequence of 2-tuples containing the group name\
along with the chunk of data.

In [ ]:
# Im confused on this one
for group_name, group_data in df.groupby('key1'):
  print((group_name, group_data))

**Step6** Group your data by `key1` and `key2`
then select `data2` and then take the mean of `data2` for each group

In [ ]:
df.groupby(['key1', 'key2'])['data2'].mean()

**Step7** Group the data below using the mapping and find the sum\
for each person across the columns, for example, a, b, and e are `red`\
c and e are `blue`, so Joe will have the sum of the columns correspoding\
to `red`columns as well as `blue` color.

In [ ]:
mapping = {
    'a': 'red',
    'b': 'red',
    'c': 'blue',
    'd': 'blue',
    'e': 'red'
}

df.groupby(mapping, axis=1).sum()

**Step8** Read the `tips.csv` dataset

In [13]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/W6/tips.csv')
df.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

**Step9** Add a tip_pct column with the tip percentage of the total bill

In [14]:
df['tip_pct'] = df['tip'] / df['total_bill'] * 100

In [19]:
df.head()

   total_bill   tip smoker  day    time  size    tip_pct
0       16.99  1.01     No  Sun  Dinner     2   5.944673
1       10.34  1.66     No  Sun  Dinner     3  16.054159
2       21.01  3.50     No  Sun  Dinner     3  16.658734
3       23.68  3.31     No  Sun  Dinner     2  13.978041
4       24.59  3.61     No  Sun  Dinner     4  14.680765

**Step10**
- Group your data by `day` and `smoker`
- Select the `tip_pct` column from this group
- Find the mean of `tcp_pct` for each grpup using `agg`function

In [22]:
df.groupby(by=['day','smoker']).agg(tip_pct_mean=('tip_pct', 'mean'))

             tip_pct_mean
day  smoker
Fri  No         15.165044
     Yes        17.478305
Sat  No         15.804766
     Yes        14.790607
Sun  No         16.011294
     Yes        18.725032
Thur No         16.029808
     Yes        16.386327

**Step11** Compute the three statistics `count`, `min`, and `max`\
for the tip_pct and total_bill columns:

In [23]:
df[['tip_pct','total_bill']].agg(['count','min','max'])

          tip_pct  total_bill
count  244.000000      244.00
min      3.563814        3.07
max     71.034483       50.81

**Step12**
- Read the dataset `stock_px.csv`
- Create a function that computes the pair-wise correlation of
  each column with the "SPX" column
- Compute percent change on close_px using pct_change

In [25]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/W6/stock_px.csv')
df.head()

            Unnamed: 0  AAPL   MSFT    XOM     SPX
0  2003-01-02 00:00:00  7.40  21.11  29.22  909.03
1  2003-01-03 00:00:00  7.45  21.14  29.24  908.59
2  2003-01-06 00:00:00  7.45  21.52  29.96  929.01
3  2003-01-07 00:00:00  7.43  21.93  28.95  922.93
4  2003-01-08 00:00:00  7.28  21.31  28.83  909.93

In [30]:
spx_corr = df[['AAPL','MSFT','XOM','SPX']].apply(lambda x: x.corr(df['SPX']))
spx_corr

AAPL    0.244478
MSFT    0.746871
XOM     0.528731
SPX     1.000000
dtype: float64

In [31]:
df.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)
df['SPX_pct_change'] = df['SPX'].pct_change()
df[['Date','SPX','SPX_pct_change']]

                     Date      SPX  SPX_pct_change
0     2003-01-02 00:00:00   909.03             NaN
1     2003-01-03 00:00:00   908.59       -0.000484
2     2003-01-06 00:00:00   929.01        0.022474
3     2003-01-07 00:00:00   922.93       -0.006545
4     2003-01-08 00:00:00   909.93       -0.014086
...                   ...      ...             ...
2209  2011-10-10 00:00:00  1194.89        0.034125
2210  2011-10-11 00:00:00  1195.54        0.000544
2211  2011-10-12 00:00:00  1207.25        0.009795
2212  2011-10-13 00:00:00  1203.66       -0.002974
2213  2011-10-14 00:00:00  1224.58        0.017380

[2214 rows x 3 columns]

**Step13**
- Extract the year part from the data index
- group by your data by year
- find the correlation of each group with `SPX`

In [37]:
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df.groupby(by='Year').apply(lambda df: df[['AAPL','MSFT','XOM']].corrwith(df['SPX']))

<ipython-input-37-b46b195f42ef>:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(by='Year').apply(lambda df: df[['AAPL','MSFT','XOM']].corrwith(df['SPX']))

          AAPL      MSFT       XOM
Year
2003  0.882692  0.675932  0.860104
2004  0.638080  0.593300  0.432642
2005  0.743263  0.746188  0.404042
2006  0.838252  0.824727  0.849528
2007  0.483093  0.292706  0.729426
2008  0.829417  0.919476  0.774885
2009  0.952895  0.950194  0.278447
2010  0.617886  0.469280  0.894656
2011 -0.552395  0.111688  0.912603

**Step14**
- A pivot table is a data summarization tool frequently found\
  in spreadsheet programs and other data analysis software.\
  It aggregates a table of data by one or more keys, arranging\
  the data in a rectangle with some of the group keys along the\
  rows and some along the columns.
- Compute a table of group means (the default pivot_table aggregation type)\
  arranged by day and smoker on the rows

In [39]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/W6/tips.csv')
df.head()

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4

In [40]:
pivot_table = df.pivot_table(values=['total_bill','tip'], index=['day','smoker'])
pivot_table

                  tip  total_bill
day  smoker
Fri  No      2.812500   18.420000
     Yes     2.714000   16.813333
Sat  No      3.102889   19.661778
     Yes     2.875476   21.276667
Sun  No      3.167895   20.506667
     Yes     3.516842   24.120000
Thur No      2.673778   17.113111
     Yes     3.030000   19.190588